# 数据源配置
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://106.52.60.176:3306/qianyu_shop?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # redis 配置
  redis:
    host: 106.52.60.176
    port: 6379
    # 如果未单独配置默认为空即可
    password: brysj$@!HHRHL
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 1000
        max-idle: 20
        min-idle: 2
    timeout: 3000
  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

# 端口配置
server:
  port: 8889

# 日志配置
logging:
  file:
    name: shop.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:SSS} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:SSS} === [%thread] === %-5level === %logger{50} === %msg%n'

jwt:
  header: Authorization
  secret: sdn#@!NYSQT
  expiration: 3600

# 支付宝支付设置
alipay:
  appId: 2021000119695837
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHDQxhG2Z9UW7W0k0jFSUTGu47SSjrhNGurv4dCcTE46S3rKmiyPpnE1E9jZwE/nS8Mjy8tNnV6VFb7MP75xa2NPzK7Bz6DBu3Wo55MxiTGRTmW6ng2ShXCwNx9xiDDMEZChEUcd6goCqfT7KeEbinRWVZCN8G/2X0azKwF163nT2RK6vtb/dT4750cNPM/vvqJBmN9CyQMCaxpJGjanZzCGI5dHtHoLgZfALTVul8QtfY0OGEpV5AOCw2TV+49+dacX+cOA/RR7qDrzEqJkb8CaaAD5fcjuZCKNpFhLGvJ7HvSQai6fncuPs0cMAmYRebdqG7Myunri8aAIjmbzD1AgMBAAECggEAMWpt3lW9FfN3fuFqwQDo2VtgNVuuSvoITEOpVnAsZ2zUYbz9yCn48En9aziSuTKqrGYUagzD37Uyu42GAi2Wl9mDwKTpdLI410YmBLTIrwwVAjNTczy2JRXY3xwm+7HY5mx3XQn/6QSaUD6q608e9nfl9zqak9Qn7YwHY2wJ2a9A/kg0gY0UmUSVoKDC8K45zc7M6EzRSUksVmLKd0zb88hZDMo6wonItQP0r8XGKwMLdDEFCwqak5X/84IwiSCloRReFhPXM0L0YL/ilEFKMVBPo5eG/o+fC96MXFT6ywwSUVBf+Mpw6wA63Rs26d/0RjgUGJdrRRniYl+h/YvXQQKBgQD6iu8fA41srkyM28S/pAk7uCp2eurp12VhKT+sKqlcO+gaNkTPbGmseJsSxDEEtDbarniknortOT074/+PW/AC8Svtap4K1a8vJYZpSrB5uuctqhuaWcTCCx7A5VYV9HRaHMcwXsNlugS0uiWUxtUl5PtPoe1vTiU2DjqSqBvGyQKBgQDLYvz4goQRxOIzn26QUFc75jA5cnxhbxWkZyUoh9arn5EdqzXYp/GK2Ej6kvbZOE8a2ke6ja5aBT2Iy93Iof3/wxWQA/D6xP6qty5MYvCGD+jGQDyklAZhFX/6bYkIS/qpZkZHCFppoTkLg+wByRyCn+m1d5eu33LjxNeMHI/yzQKBgQCPN9JfITG72ZsKviom/ocEq08isTsN90INm325Vh3ACsKwESuegrOZksvam2oF7VqaATgXqkVyO9EkJj4VXhHCLMjWi6bSPLpKsiG2mKpuu4ehE+d5gS03WxH2ZGKkZDwKsv6uSM1bnk1IXkxTUqHPaqi6Ka9HfB1LXDDhWtWd+QKBgQCXeSSgTEviE/jHq6CjeEJPyRL3Ze1+f0XmCC+jbO+TKCbiqsVSk1mQJ57Kh7OyeX5oqFKtfKFyR97ZR8PojcTmu7sOY/EQQrDMIdsoZrNtlOGu7N59UAUkPufuca+R70xC53nFo1H6w2kBy4F0nvxNyJ09WlEsmxwsyEgkAI2wrQKBgDr3iIL5WUDIkLv3vpArA49VujEiz1edxlNHKiByTt24u/mDCG3/k5cVi13rtFp/uSgtBFs360p4Q1vUsvDADHXLp+R8GcamwJREK3F313LnZaJijN82Do0tzYf3kY3zBNg0yXOB25p3LeXFqusXWlsLxykWJ7xWBagyN6O/4rwu
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxw0MYRtmfVFu1tJNIxUlExruO0ko64TRrq7+HQnExOOkt6yposj6ZxNRPY2cBP50vDI8vLTZ1elRW+zD++cWtjT8yuwc+gwbt1qOeTMYkxkU5lup4NkoVwsDcfcYgwzBGQoRFHHeoKAqn0+ynhG4p0VlWQjfBv9l9GsysBdet509kSur7W/3U+O+dHDTzP776iQZjfQskDAmsaSRo2p2cwhiOXR7R6C4GXwC01bpfELX2NDhhKVeQDgsNk1fuPfnWnF/nDgP0Ue6g68xKiZG/AmmgA+X3I7mQijaRYSxryex70kGoun53Lj7NHDAJmEXm3ahuzMrp64vGgCI5m8w9QIDAQAB
  notifyUrl: http://localhost:8888
  returnUrl: http://localhost:8888/#/Paid
  signType: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  logPath: E:\\文件\\毕业设计\\qainyu-shop\\shop-server\\
